mod 'puppet/nginx', '1.0.0'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs/translate'
mod 'puppetlabs/reboot'
mod 'puppetlabs/powershell'
mod 'puppet/yum'
mod 'puppetlabs/docker'
mod 'samuelson/dockeragent'

